### PR TITLE
V2 CLI: Add external commands

### PR DESCRIPTION
**Pull request by rm-dr**
Implemented the feature proposed in #737.
Is it really that easy?

**A question:**
Should `v2_main` exit earlier if an external command is given?
We probably don't need to set up colors and customizations if we're running an external command.

### CODE REVIEW

**Comment by ColeFrench** [comment]
Cool! I think you should add tests with a dummy external subcommand, and document this feature.

**Comment by pkgw** [comment]
Thanks! I'm going to close and reopen this to rerun the CI to check that this still builds cleanly against the latest `master`.

**Comment by pkgw** [comment]
Agreed that it would be good to add test coverage for this, although I admit that it might take a fair amount of work to implement for relatively small benefit. It might be helpful to see if Cargo has a clever, lightweight way for testing this kind of functionality.

One further ask that's a little bit more important to me would be updating the documentation somewhere to mention this capability. I'm not sure if there's a single best place in the docs to describe it, but ideally it should be described somewhere.

**Comment by pkgw** [comment]
The Azure Pipelines CI failures are spurious — a side effect of me merging another PR while this one was running. They should go away with the next fresh CI build.

**Pull request merged**
