### PR TITLE
fix: use c++ 17

### LINKED ISSUE #1178: Can build standalone but not as dependency
I'm trying to embed Tectonic in another program but am running into build issues that I can't quite pin down... 

I'm building on macOS with dependencies installed via Homebrew. 

This works just fine:
```
git clone https://github.com/tectonic-typesetting/tectonic
cd tectonic
git submodule update --init
PKG_CONFIG_PATH=$(brew --prefix icu4c)/lib/pkgconfig cargo build
```

But this fails:
```
cargo new tectonic-embed
cd tectonic-embed
cargo add tectonic
PKG_CONFIG_PATH=$(brew --prefix icu4c)/lib/pkgconfig cargo build
```

With trouble building the vendored HarfBuzz, it looks like. 
```
[snip]
error: failed to run custom build command for `tectonic_bridge_harfbuzz v0.2.9`

Caused by:
  process didn't exit successfully: `/Users/shane/Projects/tectonic-embed/target/debug/build/tectonic_bridge_harfbuzz-e78f2c9e3f07e8a3/build-script-build` (exit status: 101)
  --- stdout
  TARGET = Some("aarch64-apple-darwin")
  OPT_LEVEL = Some("0")
  HOST = Some("aarch64-apple-darwin")
  cargo:rerun-if-env-changed=CXX_aarch64-apple-darwin
  CXX_aarch64-apple-darwin = None
  cargo:rerun-if-env-changed=CXX_aarch64_apple_darwin
  CXX_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_CXX
  HOST_CXX = None
  cargo:rerun-if-env-changed=CXX
  CXX = None
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  cargo:rerun-if-env-changed=CXXFLAGS_aarch64-apple-darwin
  CXXFLAGS_aarch64-apple-darwin = None
  cargo:rerun-if-env-changed=CXXFLAGS_aarch64_apple_darwin
  CXXFLAGS_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_CXXFLAGS
  HOST_CXXFLAGS = None
  cargo:rerun-if-env-changed=CXXFLAGS
  CXXFLAGS = None
  cargo:rerun-if-env-changed=AR_aarch64-apple-darwin
  AR_aarch64-apple-darwin = None
  cargo:rerun-if-env-changed=AR_aarch64_apple_darwin
  AR_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_AR
  HOST_AR = None
  cargo:rerun-if-env-changed=AR
  AR = None
  cargo:rerun-if-env-changed=ARFLAGS_aarch64-apple-darwin
  ARFLAGS_aarch64-apple-darwin = None
  cargo:rerun-if-env-changed=ARFLAGS_aarch64_apple_darwin
  ARFLAGS_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_ARFLAGS
  HOST_ARFLAGS = None
  cargo:rerun-if-env-changed=ARFLAGS
  ARFLAGS = None
  cargo:rustc-link-lib=static=harfbuzz
  cargo:rustc-link-search=native=/Users/shane/Projects/tectonic-embed/target/debug/build/tectonic_bridge_harfbuzz-d62862240405c468/out
  cargo:rerun-if-env-changed=CXXSTDLIB_aarch64-apple-darwin
  CXXSTDLIB_aarch64-apple-darwin = None
  cargo:rerun-if-env-changed=CXXSTDLIB_aarch64_apple_darwin
  CXXSTDLIB_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_CXXSTDLIB
  HOST_CXXSTDLIB = None
  cargo:rerun-if-env-changed=CXXSTDLIB
  CXXSTDLIB = None
  cargo:rustc-link-lib=c++
  cargo:include-path=/Users/shane/Projects/tectonic-embed/target/debug/build/tectonic_bridge_harfbuzz-d62862240405c468/out;/opt/homebrew/Cellar/graphite2/1.3.14/include

  --- stderr
  thread 'main' panicked at /Users/shane/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tectonic_bridge_harfbuzz-0.2.9/build.rs:143:47:
  failed to copy header: Os { code: 2, kind: NotFound, message: "No such file or directory" }
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I noted [this discussion](https://github.com/tectonic-typesetting/tectonic/issues/1172) where the problem was resolved by enabling `external-harfbuzz` but that just seems to have a different set of build issues where it looks like the XeTeX build is looking for `<harfbuzz/hb.h>` but the pkg-config include flag is already pointing to the `harfbuzz` directory so it's missing the header: 
```
[snip]
The following warnings were emitted during compilation:

warning: tectonic_xetex_layout@0.2.4: In file included from layout/xetex-XeTeXFontInst.cpp:42:
warning: tectonic_xetex_layout@0.2.4: layout/tectonic_xetex_layout.h:42:10: fatal error: 'harfbuzz/hb.h' file not found
warning: tectonic_xetex_layout@0.2.4: #include <harfbuzz/hb.h>
warning: tectonic_xetex_layout@0.2.4:          ^~~~~~~~~~~~~~~
warning: tectonic_xetex_layout@0.2.4: 1 error generated.

error: failed to run custom build command for `tectonic_xetex_layout v0.2.4`
```

I was about to start mucking around with CFLAGS but figured there might be some deeper issue I'm missing, at least with regard to getting the vendored version building properly when the Tectonic is a dependency.

### LINKED ISSUE #1184: Tectonic 0.15.0 build fails
Tectonic build fails at "tectonic_xetex_layout v0.2.4" step with the following error:

error: failed to run custom build command for `tectonic_xetex_layout v0.2.4 (/home/user/RPM/SOURCES/tectonic-tectonic-0.15.0/crates/xetex_layout)`

thread 'main' panicked at crates/xetex_layout/build.rs:79:73:
  called `Result::unwrap()` on an `Err` value: NotPresent
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

Line  79  in `crates/xetex_layout/build.rs` 
is as follows:
  `let graphite2_include_path = env::var("DEP_GRAPHITE2_INCLUDE_PATH").unwrap();`

### LINKED ISSUE #1190: build fails with icu 75
Building with recent icu 75.1/harfbuzz-icu give this build failure:

```
   Compiling tracing v0.1.40
The following warnings were emitted during compilation:

warning: tectonic_xetex_layout@0.2.4: In file included from /usr/include/unicode/ubidi.h:26,
warning: tectonic_xetex_layout@0.2.4:                  from layout/xetex-XeTeXLayoutInterface.cpp:36:
warning: tectonic_xetex_layout@0.2.4: /usr/include/unicode/localpointer.h:561:26: error: ‘auto’ parameter not permitted in this context
warning: tectonic_xetex_layout@0.2.4:   561 | template <typename Type, auto closeFunction>
warning: tectonic_xetex_layout@0.2.4:       |                          ^~~~
warning: tectonic_xetex_layout@0.2.4: /usr/include/unicode/localpointer.h:573:76: error: template argument 2 is invalid
warning: tectonic_xetex_layout@0.2.4:   573 |     explicit LocalOpenPointer(std::unique_ptr<Type, decltype(closeFunction)> &&p)
warning: tectonic_xetex_layout@0.2.4:       |                                                                            ^
warning: tectonic_xetex_layout@0.2.4: /usr/include/unicode/localpointer.h:583:78: error: template argument 2 is invalid
warning: tectonic_xetex_layout@0.2.4:   583 |     LocalOpenPointer &operator=(std::unique_ptr<Type, decltype(closeFunction)> &&p) {
warning: tectonic_xetex_layout@0.2.4:       |                                                                              ^
warning: tectonic_xetex_layout@0.2.4: /usr/include/unicode/localpointer.h:599:59: error: template argument 2 is invalid
warning: tectonic_xetex_layout@0.2.4:   599 |     operator std::unique_ptr<Type, decltype(closeFunction)> () && {
warning: tectonic_xetex_layout@0.2.4:       |                                                           ^
warning: tectonic_xetex_layout@0.2.4: /usr/include/unicode/ubidi.h:579:1: note: invalid template non-type parameter
warning: tectonic_xetex_layout@0.2.4:   579 | U_DEFINE_LOCAL_OPEN_POINTER(LocalUBiDiPointer, UBiDi, ubidi_close);
warning: tectonic_xetex_layout@0.2.4:       | ^~~~~~~~~~~~~~~~~~~~~~~~~~~

error: failed to run custom build command for `tectonic_xetex_layout v0.2.4 (/build/tectonic/src/tectonic-tectonic-0.15.0/crates/xetex_layout)`

Caused by:
  process didn't exit successfully: `/build/tectonic/src/tectonic-tectonic-0.15.0/target/release/build/tectonic_xetex_layout-2d264a57173811f7/build-script-build` (exit status: 1)
```

### PR DESCRIPTION
**Pull request by winstxnhdw**
Closes #1190
Closes #1184
Closes #1178

### CODE REVIEW

**Comment by CraftSpider** [comment]
Thank you for your work on this! I'll merge this once I find time to review it.

**Comment by winstxnhdw** [comment]
FWIW, it is working fine on my [project](https://github.com/winstxnhdw/tectonic-api).

**Comment by CraftSpider** [comment]
I'm not worried about the coverage failure personally - a decrease of `.06` isn't really a big deal, and the clippy fixes I'm guessing just altered line hits slightly.

**Comment by inferiorhumanorgans** [comment]
This does not fix #1178.

**Comment by winstxnhdw** [comment]
> This does not fix #1178 (regardless of whether or not `external-harfbuzz` is enabled).

Are you on MacOS?

**Comment by sjml** [comment]
For what it's worth, this built successfully for me. (I have not explored further or tried to use it; not much bandwidth at the moment. But it does look like the fixes in this repo let it build.) I'm on macOS, for whatever that's worth. 

```
cargo new tectonic-embed
cd tectonic-embed
cargo add --git https://github.com/winstxnhdw/tectonic tectonic
PKG_CONFIG_PATH=$(brew --prefix icu4c)/lib/pkgconfig cargo build
```

**Comment by inferiorhumanorgans** [comment]
> > This does not fix #1178 (regardless of whether or not `external-harfbuzz` is enabled).
> 
> Are you on MacOS?

Yes.

If I don't set `PKG_CONFIG_PATH` it can't/won't find the `icu-uc` files.  If I do and use `external-harfbuzz`, the build fails because it can't find the headers, if I use the vendored harfbuzz it links against the system icu and spits out a bunch of undefined symbols.

**Comment by sjml** [comment]
> > > This does not fix #1178 (regardless of whether or not `external-harfbuzz` is enabled).
> > 
> > 
> > Are you on MacOS?
> 
> Yes. 14.3.
> 
> If I don't set `PKG_CONFIG_PATH` it can't/won't find the `icu-uc` files. If I do and use `external-harfbuzz`, the build fails because it can't find the headers, if I use the vendored harfbuzz it links against the system icu and spits out a bunch of undefined symbols.

The `PKG_CONFIG_PATH` variable will probably always be needed on macOS builds because the system includes old headers that would get picked up otherwise. 

The problem with external harfbuzz probably needs to be figured out, though, but it's at least separate from #1178. I was just verifying that this PR does in fact close that issue that I opened.

**Comment by inferiorhumanorgans** [comment]
Well, no.  I literally described the exact problems #1178 describes.  Those still persist with winstxnhdw/master.

**Comment by sjml** [comment]
> Well, no. I literally described the exact problems #1178 describes. Those still persist with winstxnhdw/master.

Sorry, I must have misread your comment. I thought you were saying it didn't work without `PKG_CONFIG_PATH`, which is expected. When I ran the console commands from [my earlier comment](https://github.com/tectonic-typesetting/tectonic/pull/1202#issuecomment-2266643072), though, it did build the project. Are you saying you get a different result from those same commands?

**Comment by winstxnhdw** [comment]
> Well, no. I literally described the exact problems #1178 describes. Those still persist with winstxnhdw/master.

Strange. It’s fine on my end as well. Might want to check if it’s something else on your end.

**Comment by inferiorhumanorgans** [comment]
> > Well, no. I literally described the exact problems #1178 describes. Those still persist with winstxnhdw/master.
> 
> Strange. It’s fine on my end as well. Might want to check if it’s something else on your end.

Right back atcha.  From looking at things, I'm not sure how it's actually building for anyone.  E.g.

https://github.com/harfbuzz/harfbuzz/blob/main/src/harfbuzz.pc.in

You can see here that pkg-config file for harfbuzz includes the harfbuzz directory (e.g. `/opt/homebrew/Cellar/harfbuzz/9.0.0/include/harfbuzz`), but one of the errors stems from `tectonic_xetex_layout.h` looking for `harfbuzz/hb.h`.

**Comment by sjml** [comment]
Can you show the actual error that you get if you run these lines? 

```
cargo new tectonic-embed
cd tectonic-embed
cargo add --git https://github.com/winstxnhdw/tectonic tectonic
PKG_CONFIG_PATH=$(brew --prefix icu4c)/lib/pkgconfig cargo build
```

**Comment by winstxnhdw** [comment]
> Right back atcha. From looking at things, I'm not sure how it's actually building for anyone. E.g.
> 
> https://github.com/harfbuzz/harfbuzz/blob/main/src/harfbuzz.pc.in
> 
> You can see here that pkg-config file for harfbuzz includes the harfbuzz directory (e.g. `/opt/homebrew/Cellar/harfbuzz/9.0.0/include/harfbuzz`), but one of the errors stems from `tectonic_xetex_layout.h` looking for `harfbuzz/hb.h`.

Well, I have a Docker build that is able to build this successfully. If you can come up with a quick Dockerfile that exhibits your issue, we can look into it.

**Comment by inferiorhumanorgans** [comment]
> Can you show the actual error that you get if you run these lines?
> 
> ```
> cargo new tectonic-embed
> cd tectonic-embed
> cargo add --git https://github.com/winstxnhdw/tectonic tectonic
> PKG_CONFIG_PATH=$(brew --prefix icu4c)/lib/pkgconfig cargo build
> ```

There's no error because tectonic is not being use and as a result the linker doesn't bother resolving tectonic's symbols.

If I invoke something from tectonic, the linker blows up with undefined symbols.  This ended up being a conflict with another crate.

If I enable the `external-harfbuzz` feature per #1178, the build fails as described.

**Comment by inferiorhumanorgans** [comment]
> > Right back atcha. From looking at things, I'm not sure how it's actually building for anyone. E.g.
> > https://github.com/harfbuzz/harfbuzz/blob/main/src/harfbuzz.pc.in
> > You can see here that pkg-config file for harfbuzz includes the harfbuzz directory (e.g. `/opt/homebrew/Cellar/harfbuzz/9.0.0/include/harfbuzz`), but one of the errors stems from `tectonic_xetex_layout.h` looking for `harfbuzz/hb.h`.
> 
> Well, I have a Docker build that is able to build this successfully. If you can come up with a quick Dockerfile that exhibits your issue, we can look into it.

Right, this is about *mac* builds with the external-harfbuzz feature enabled.  On a Linux system (e.g. docker) harfbuzz is probably being installed into a path that the compiler is already searching e.g. `/usr/include`.  Take a look at the harfbuzz pkg-config files I linked to above.  They append the harfbuzz subdirectory to the compiler search path.  Now look at how tectonic refers to the harfbuzz headers.  Tectonic assumes that the harfbuzz subdirectory is not part of the compiler's search path.

This pull request doesn't fix the problems described in #1178.

**Comment by sjml** [comment]
If I use this `main.rs` file, it compiles and runs just fine provided I continue to give the appropriate PKG_CONFIG_PATH variable. 

```rust
use tectonic;

fn main() {
    let latex = r#"
    \documentclass{article}
    \begin{document}
    Hello, world!
    \end{document}
    "#;

    let pdf_data: Vec<u8> = tectonic::latex_to_pdf(latex).expect("processing failed");
    println!("Output PDF size is {} bytes", pdf_data.len());
}
```

```
> PKG_CONFIG_PATH=$(brew --prefix icu4c)/lib/pkgconfig cargo build
[...]
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 33.64s
```

Running through cargo also needs the environment variable: 
```
> PKG_CONFIG_PATH=$(brew --prefix icu4c)/lib/pkgconfig cargo build
[...]
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 20.07s
     Running `target/debug/tectonic-embed`
Output PDF size is 3031 bytes
```

But the created executable runs just fine:
```
> ./target/debug/tectonic-embed
Output PDF size is 3031 bytes
```

**Comment by CraftSpider** [comment]
Upon review, this looks good to me. I'm not able to speak to the PKG_CONFIG failures right now, but the changes in this are at least necessary to fix some issues, and this is a good prerequisite for #1209. As such, I'm going to merge, but feel free to re-open any issues that appear to still occur.

**Pull request merged**
