### PR TITLE
Update hyper-native-tls to 0.3

### PR DESCRIPTION
**Pull request by Mrmaxmeier**
This updates the transitive dependency `openssl-sys` from `0.9` to `0.10`.
`openssl-sys` adds support for linking OpenSSL 1.1.

Arch Linux recently updated its version of OpenSSL to 1.1.1.
Here's the build error message for posterity:
```
error: failed to run custom build command for `openssl v0.9.24`                                            
process didn't exit successfully: `/tmp/tectonic/target/debug/build/openssl-a86acbb03e68eef0/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to detect OpenSSL version', /home/mrmaxmeier/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.9.24/build.rs:16:14
```

### CODE REVIEW

**Comment by pkgw** [comment]
Looks good, thanks!

**Comment by pkgw** [comment]
@Mrmaxmeier Oh: would it be helpful to roll a new release containing this change?

**Comment by Arvedui** [comment]
Yes!
Of course it could be patched in the packaging script, but a compatible and official release would imho be better.

**Comment by polyzen** [comment]
Yes, please make another release.

**Comment by pkgw** [comment]
I've just published version 0.1.10.

**Pull request merged**
