### PR TITLE
tectonic/ cleanups

### PR DESCRIPTION
**Pull request by ronnychevalier**
Some cleanups of the `tectonic/` folder.

### CODE REVIEW

**Comment by ronnychevalier** [comment]
@pkgw Are you interested in cleanups to improve the overall quality of the C code of `tectonic/`, but different than just warning fixes? It could be quite a long term goal, but it could be worth it.

As if I understood correctly, one goal of tectonic would be to have a modernized TeX engine. Improving the quality of the C code could help later to export some functionality from C to Rust code. However, improving the quality of the code (i.e., more than just removing dead code) could introduce bugs from time to time.

So is the goal of tectonic to also improve the quality of the C engine?

**Comment by rekka** [comment]
I would also like to see improvements to the C code over time. I am quite excited for instance about the possibility of adding more hooks in the xetex engine so that tectonic can generate better error messages.

However, parts of the C code of xetex and bibtex that tectonic is using is a code generated by the `web2c` tool from the original `WEB` code, see [tectonic-staging](https://github.com/tectonic-typesetting/tectonic-staging). I am curious whether edits to the C code do not make it more difficult to pull bugfixes from the upstream branch of xetex, see for instance #61 .

**Comment by pkgw** [comment]
Yes, the goal is definitely to clean up the C code.

The plan for bugfixing is that the "base" code for Tectonic is tracked in [tectonic-staging/products/](https://github.com/tectonic-typesetting/tectonic-staging/tree/master/products) — these files can be generated automatically by pulling in from the TeXLive repository, and they do not get edited. They *do* get tracked in Git.

When updates occur, you therefore can see what changed in the files in `products/`. The idea is that you then manually port the changes over to the main [tectonic/tectonic/](https://github.com/tectonic-typesetting/tectonic/tree/master/tectonic) tree. The bet is that most of the code in the TeXLive branch will change slowly (if at all) so this won't be *too* onerous.

Once the updates are integrated into the Tectonic mainline, the new files in `products/` are committed to mark that they are the new baseline for the C code.

Once I get some spare time I plan to work through this process to pull in the latest XeTeX updates and see how it works in practice ...

**Comment by pkgw** [comment]
As for the actual changes here in this PR, I like them and learned a few things!

- I didn't know that C functions are automatically treated as `extern`
- I thought that `char const *` meant `char * const`, but apparently it means `const char *`

Given all that I'm going to go ahead and merge. Thanks!

**Comment by rekka** [comment]
Thanks for the detailed explanation. It makes a lot of sense. It might be worth putting it in the [`tectonic/tectonic-staging/README.md`](https://github.com/tectonic-typesetting/tectonic-staging).

Resolving #61 will be a good test.

**Pull request merged**
