### PR TITLE
Add pdf crop #748

### PR DESCRIPTION
**Pull request by AlongWY**
look as #748;

### CODE REVIEW

**Comment by pkgw** [comment]
Thanks for submitting this! This is a very interesting idea.

I want to think a bit about the design here and different ways it could be approached. In the issue you wrote that you made two versions, "It is a standalone one, but it's too big." Can you explain a bit more about what you mean by that? I am not sure that I understand.

**Comment by AlongWY** [comment]
The standalone version use tectonic as a library, the size of compiled binary is same as tectonic, about 11MB.
I think it’s not worth that, so I think maybe the pdfcrop can be a part of tectonic.

**Comment by AlongWY** [comment]
And I will rebase the repo later.

**Comment by pkgw** [comment]
OK, I think I understand now. Thank you for the explanation.

After thinking about this for a bit, the main thing on my mind is that I really do not want Tectonic to depend on GhostScript. This is because that *any* external dependency limits Tectonic's ability to run in different environments (e.g., WASM), and also because I am very worried about the security qualities of GhostScript in particular. In this case, GhostScript is being used in a controlled way so I think that the security implications are not problematic, but I don't want to encourage people to depend on it in their workflows.

Because the functionality in this pull request is not essential to running the Tectonic engine, I think it would be better to keep it in a separate piece of code — either option (1) or (2) that you listed above. I agree that the binary size becomes pretty unreasonable when you link against Tectonic directly, and that's unfortunate.

For use cases like this, it might be very helpful for Tectonic to provide some kind of `tectonic_client` crate that can provide a Rust interface for driving the `tectonic` executable in a structured way. That would help people take advantage of Tectonic typesetting capabilities without having to compile and link in the entire software stack directly, which, as we are seeing here, is a lot to ask for many applications. It wouldn't be able to handle as many use cases as direct linking, but perhaps it would meet a lot of needs in a much more convenient way. Would you be interested in working together to create such a crate?

**Comment by AlongWY** [comment]
I think this is a good idea.
I'll probably finish this in the next few weeks.

**Pull request closed without merging**
