### PR TITLE
Fix whitespace issues

### PR DESCRIPTION
**Pull request by Mrmaxmeier**
Hey,
while strolling through the codebase I noticed some inconsistencies in indentation.
I wrote a little script to fix the mixed indentation and remove trailing whitespace.
I guess [elastic tabstops](http://nickgravgaard.com/elastic-tabstops/) aren't a thing yet so this might be the best compromise.

-   There are still some inconsistencies left to fix
    (`Engine.*`, `TECkit_*` and the data table files are left untouched)
- [x] The changes should probably be split up into commits of different importance
- [x] The changes to Engine{.cpp,.h} are mostly opinionated and should probably not be included
- [x] ~Try not to overshadow `git-blame`~ TIL: `git blame -w`

### CODE REVIEW

**Comment by pkgw** [comment]
Thanks for taking a look at this. I have been slowly reformatting some of the C files as I touch them, but I've barely looked at the xdvipdfmx files (`dpx-*`) since the bulk of my work has not yet involved them.

I'm not able to merge this right now since I'm not in a position to examine the changes in detail, and I'd like to do that before merging. But, re: your WIP items — are there additional commits you'd like to add to this PR, or do you think this should be mergeable as-is?

**Comment by Mrmaxmeier** [comment]
@pkgw I'll add commits and ping you once I think the Pull Request is ready to be reviewed.

**Comment by pkgw** [comment]
OK. Just as a heads-up, I'm doing a fair amount of work on the C code these days, which might be a bit annoying for you to track as you work on your patches. But, whenever you're happy with your PR, I'll try to review and integrate it quickly so that it doesn't fall `master`.

**Comment by Mrmaxmeier** [comment]
I've reduced this Pull Request to reasonable and hopefully easily review-able commits. Feel free to merge it when its most convenient.

**Comment by pkgw** [comment]
Merged. Thanks!

**Pull request merged**
