### PR TITLE
static builder on travis

### PR DESCRIPTION
**Pull request by malbarbo**
Includes https://github.com/tectonic-typesetting/tectonic/pull/259

### CODE REVIEW

**Comment by malbarbo** [comment]
The next step to fix https://github.com/tectonic-typesetting/tectonic/issues/185 is to deploy the static build. But I don't shown how to do it.

**Comment by pkgw** [comment]
Cool, thanks! Let's hold this until #259 converges.

**Comment by pkgw** [comment]
I've pushed an update that rebases this on #261 and makes some tweaks that I think tighten things up a bit. @malbarbo let me know what you think about these changes?

**Comment by malbarbo** [comment]
@pkgw It's look great to me! Thanks for working on this.

**Pull request merged**
