### PR TITLE
Catch the engine(s) up to TeXLive 2020.0

### PR DESCRIPTION
**Pull request by pkgw**
At long last, let's start the work to catch the Tectonic engine implementations up to TeXLive 2020.0.

- [x] xvipdfmx
- [x] bibtex
- [x] synctex
- [x] teckit
- [x] xetex

CC @Mrmaxmeier @crlf0710 tectonic-typesetting/tectonic-staging#8

### CODE REVIEW

**Comment by pkgw** [comment]
Current status: new xdvipdmx passes the test suite on my Linux laptop. We'll see how it fares in the CI battery ...

**Comment by Mrmaxmeier** [comment]
Hmm, this causes a bunch of SIGABRTs and SIGSEGVs:
https://tt.ente.ninja/#/compare/tectonic@0.1.17/d47454ba362b95bb9191835a27f6e555478e903d

I'll add [the tectonic-on-arXiv bot](https://github.com/apps/tectonic-ci) to this repo to simplify tracking down these issues.

**Comment by pkgw** [comment]
Windows vcpkg builds are current failing due to an unrelated issue: https://github.com/microsoft/vcpkg/issues/13286, addressed by https://github.com/microsoft/vcpkg/pull/13298 .

**Comment by pkgw** [comment]
@Mrmaxmeier OK, I installed the app on this repo. Do I need to do any further configuration?

**Comment by Mrmaxmeier** [comment]
> @Mrmaxmeier OK, I installed the app on this repo. Do I need to do any further configuration?

No. It's supposed to just work :tm: after installing. The whole thing is pretty hacky at the moment though and I'll need to manually add each fork for it to pull the new commits.

**Comment by pkgw** [comment]
@Mrmaxmeier Should I just rename this branch? That feels like it would be the most TeX-esque solution ...

**Comment by Mrmaxmeier** [comment]
I'll fix it in the bot. The GitHub API for custom checks has improved a bunch since I hacked it together.
It looks like the relevant information is now included in the web-hook payload, so I'll use that instead of searching the git tree locally :+1:

**Comment by pkgw** [comment]
Looks like it's running now, super cool!

**Comment by pkgw** [comment]
@Mrmaxmeier There was one big typo that caused the vast majority of the regressions. Now there are only a handful, but I can't reproduce them locally — my build of the CLI program handles them successfully. Do you have a sense of what the might be going on if your tool reports internal errors that don't reproduce in the CLI?

**Comment by Mrmaxmeier** [comment]
The CI bot runs release builds in a Ubuntu 20.10 docker. Reproducability issues are probably either different system libraries (It'd be nice statically link harfbuzz) or some form of UB.
I tried reproducing `1702.05081` locally and it segfaults due to an uninitialized(?) char-pointer:
```
gef➤  
#1  0x00005555557675f0 in save_font () at tectonic/dpx-mpost.c:159
159	    next->font_name = NEW(strlen(current->font_name)+1, char);
gef➤  p current->font_name
$5 = 0x4052000000000000 <error: Cannot access memory at address 0x4052000000000000>
```

**Comment by pkgw** [comment]
Almost there! We just need to fix the Arxiv regressions and actually implement the new I/O primitives.

**Comment by pkgw** [comment]
@Mrmaxmeier looks like the crashes are now fixed!

**Comment by pkgw** [comment]
@Mrmaxmeier The last few builds generated internal errors for the tectonic-on-arXiv bot :-( Did I break your service?

**Comment by pkgw** [comment]
I believe that this is now ready to go! Modulo the fact that we should always have more test coverage and the Arxiv tester seems to be broken at the moment.

**Comment by pkgw** [comment]
Reran the TeXLive 2020 bundle tests with this version of the engine. Ten more classes compile now, and there are no new failures, so that's a good sign.

**Comment by pkgw** [comment]
Going to try to retrigger the tectonic-on-arXiv bot since it looks like it may have been fixed a few hours ago.

**Pull request merged**
