### PR TITLE
Fix build for rust 1.80 by bumping `time` crates

### LINKED ISSUE #1207: rust 1.80.0 build issue
seeing some build failure as

```
error[E0282]: type annotations needed for `Box<_>`
  --> /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.34/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
help: consider giving `items` an explicit type, where the placeholders `_` are specified
   |
83 |     let items: Box<_> = format_items
   |              ++++++++
```

see https://github.com/time-rs/time/issues/693

### PR DESCRIPTION
**Pull request by bryango**
Fixes #1207. The build fails with rust 1.80 due to an outdated `time` crate. This can be simply fixed by `cargo update time`.

This issue would soon affect _all_ downstream (distro) packagers, and the fix is rather trivial and minimal, so I hope it can be fast-tracked into master (after CI of course). A bugfix release would be even better, but it's your decision! @CraftSpider @rm-dr 

See:
- https://github.com/tectonic-typesetting/tectonic/issues/1207
- https://github.com/time-rs/time/issues/693
- https://github.com/NixOS/nixpkgs/issues/332957
- log: https://hydra.nixos.org/build/268733905/nixlog/1

### CODE REVIEW

**Comment by CraftSpider** [comment]
I just merged #1202, which should fix the unrelated build and clippy failures

**Comment by bryango** [comment]
Ah thank you very much! This seems to have the working `time` crate now. Would you be interested in a minor bugfix release? Maybe we shall ping @pkgw?

**Comment by CraftSpider** [comment]
pkgw would be the right person, I personally don't know the release process yet.

**Comment by bryango** [comment]
The relevant fix is now available in `master` at 6b49ca8db40aaca29cb375ce75add3e575558375. Before a proper release @pkgw , downstream may simply cherry-pick this commit. I have checked that it applies nicely on top of https://github.com/tectonic-typesetting/tectonic/tree/tectonic%400.15.0

**Comment by pkgw** [comment]
Sorry for being completely AWOL on all this :frowning_face: 

I'll make a release soon, and demonstrate the process. With the release automation tools that we have, it can be quite straightforward, although there are a few concepts to learn.

**Pull request closed without merging**
