### PR TITLE
terrible hacks for depending upon crateized harfbuzz/graphite2.

### PR DESCRIPTION
**Pull request by ratmice**
This is a pretty terrible hack, mainly meant as an RFC/not intended to be merged in it's current form.

I was working on getting CI up for my project which depends tectonic,
Somwhere in that process I figured it'd be really nice if we could just depend upon a harfbuzz crate,
and let cargo sort out the dependencies for that system library.

Tectonic itself depends upon harfbuzz and graphite2 directly,
It also relies upon the headers hb-icu.h and hb-graphite2.h, so requires a harfbuzz which has been built against ICU and graphite2.

(So as such graphite is both a direct, and transitive dependency through harfbuzz).

Anyhow, most of the work that needs to be done is probably in the harfbuzz crate itself,
but the ICU/graphite2 crates required some changes as well.

But at least here is a hack which works on exactly 1 system configuration i have tried
when there is no system harfbuzz headers installed.

### CODE REVIEW

**Comment by pkgw** [comment]
Thanks for submitting! This is certainly an area where I wish we had a bit of a nicer story.

Do the `DEP_*` environment variables get set automatically when `harfbuzz-sys` is included as a dependency, or is the idea that they'd be set externally when building Tectonic?

There are times when I start feeling that maybe we should just bundle the source code for Harfbuzz, Graphite, and maybe some of the other deps, and compile them all ourselves. That does not feel awesome, but to be honest it might make life easier in some ways — those libraries are, fortunately, nice and straightforward to compile.

The other thing is that if we could isolate the cross-coupling between Tectonic's C/C++ code and the headers of Harfbuzz and friends, that would simplify some things. That ties into a somewhat distinct goal: I'd like to start replacing common subsystems in Tectonic's C/C++ code (e.g., image loading) with versions written in Rust, and due to the spaghetti nature of the code, those subsystems would have to be callable from C/C++. So you could imagine a low level foundation written in Rust, that generates a C header file, that the C/C++ code compiles against, that then is compiled into the final Rust crate. And you could further imagine having that low level foundation depend on Harfbuzz and friends, adding yet another layer to the stack. Convoluted, but I have a feeling that might be the only path forward to Rustifying large chunks of the code. (See @Mrmaxmeier's #246 for an example of making Rust callable from C.)

**Comment by ratmice** [comment]
> Thanks for submitting! This is certainly an area where I wish we had a bit of a nicer story.
> 
> Do the `DEP_*` environment variables get set automatically when `harfbuzz-sys` is included as a dependency, or is the idea that they'd be set externally when building Tectonic?

These are set by cargo automatically,
Lines from harfbuzz-sys/build.rs like:
```rust
    println!("cargo:include={}", out_dir.join("include").join("harfbuzz").display());
```
will correlate to DEP_HARFBUZZ_INCLUDE, somehow cargo will pull the harfbuzz out of name of the library being linked, so this sets the environment variable:

DEP_HARFBUZZ_INCLUDE=/path/to/outdir/include/harfbuzz

in my patch I used a few non-standard variables (include_flags, link_flags, libdir_flags),
these are essentially derived from cargo by the line:
println!("cargo:include_flags={}", include_flags);

I used these nonstandard flags, because the standard cargo:include I think wants a single directory
but when things come from pkg-config and the like there may be multiple -I/-L directories or -l libs.

> There are times when I start feeling that maybe we should just bundle the source code for Harfbuzz, Graphite, and maybe some of the other deps, and compile them all ourselves. That does not feel awesome, but to be honest it might make life easier in some ways — those libraries are, fortunately, nice and straightforward to compile.

Indeed i think this would help, I feel fairly soundly defeated at the moment by the system distributed versions of these libraries in the failed attempts to build on the CI where system libraries are being found.

On the windows CI the system harfbuzz seems to link to glib, but I hadn't figured out where to get a -lglib flag from, On linux/pkg-config, the existing pkg-config probe's return *before* println'ing any of those environment variables (and thus they don't get set by cargo). Making that pkg-config branch println stuff/to export DEP_* I encounter some linkage issue I don't yet fully comprehend.

So at least for the moment being it'd be great if I could establish a baseline of just bundling all the sources, then perhaps add system-library stuff back in on top of that.

> The other thing is that if we could isolate the cross-coupling between Tectonic's C/C++ code and the headers of Harfbuzz and friends, that would simplify some things. That ties into a somewhat distinct goal: I'd like to start replacing common subsystems in Tectonic's C/C++ code (e.g., image loading) with versions written in Rust, and due to the spaghetti nature of the code, those subsystems would have to be callable from C/C++. So you could imagine a low level foundation written in Rust, that generates a C header file, that the C/C++ code compiles against, that then is compiled into the final Rust crate. And you could further imagine having that low level foundation depend on Harfbuzz and friends, adding yet another layer to the stack. Convoluted, but I have a feeling that might be the only path forward to Rustifying large chunks of the code. (See @Mrmaxmeier's #246 for an example of making Rust callable from C.)

Indeed I haven't much looked in that regard, A bit afraid that snowball might start rolling downhill :mountain_snow:

**Comment by spl** [comment]
@ratmice I see you've [forked](https://github.com/ratmice/graphite2-sys-rust) my [`graphite2-sys-rust`](https://github.com/spl/graphite2-sys-rust) repository. I've actually been working on that explicitly for supporting Tectonic. I'm also still working on it, so it's not ready to be released. I plan on doing some other `-sys` crates before introducing it to Tectonic.

**Comment by spl** [comment]
> There are times when I start feeling that maybe we should just bundle the source code for Harfbuzz, Graphite, and maybe some of the other deps, and compile them all ourselves. That does not feel awesome, but to be honest it might make life easier in some ways — those libraries are, fortunately, nice and straightforward to compile.

@pkgw The nice thing about putting them in crates (in the way I see it at least) is that the crate allows you to choose whether to use a bundled, statically linked library or a shared, dynamically linked library. Thus, you can configure this transitively from the `tectonic` crate. Plus, all the build settings are localized to the crate itself instead of being lumped in with the rest of  Tectonic.

**Comment by ratmice** [comment]
@spl sorry I should have mentioned that this entailed a fork of your work earlier. I was mostly just curious how close we were from a standalone 'cargo install', and tend to work from the backwards from the goal.  I don't mean to step on any toes, and apologize if that is the case.

**Comment by spl** [comment]
@ratmice No offense taken. I just wanted to note that it's not ready, yet.

I have also been working through the issues with `graphite2` to figure out how to successfully install it on different targets and with different mechanisms (static, shared, `pkg-config`, `vcpkg`, `homebrew`, etc.) Once I'm done there, I plan to apply the same approach to other libraries: `freetype2`, `harfbuzz`, `icu`. Once that is done, I believe it will be ready for Tectonic.

**Comment by pkgw** [comment]
@spl Ah, cool to hear that you've been looking at this problem too! I've always believed that the fundamental blocker on using dep crates like `harfbuzz-sys` has been getting the compiler flags so that Tectonic's C/C++ code can find the necessary headers, but I didn't know abut the `DEP_*` variables. It sounds like those might provide a nice path forward.

An extra Tectonic-specific wrinkle might be that we need a Harfbuzz that's been built with Graphite2 support. I do not know how common it is for packagers to include that feature.

**Comment by spl** [comment]
> I've always believed that the fundamental blocker on using dep crates like `harfbuzz-sys` has been getting the compiler flags so that Tectonic's C/C++ code can find the necessary headers, but I didn't know abut the `DEP_*` variables. It sounds like those might provide a nice path forward.

@pkgw Yes, a `DEP_` env var works for the include file path.

> An extra Tectonic-specific wrinkle might be that we need a Harfbuzz that's been built with Graphite2 support. I do not know how common it is for packagers to include that feature.

FYI, the [`servo/rust-harfbuzz`](https://github.com/servo/rust-harfbuzz) crate includes the following `configure` flags, among others: `--without-icu --without-freetype --without-glib`

After finishing `graphite2`, I will look into `freetype`, `icu`, and `harfbuzz` in a way that allows them to be configured and used by Tectonic (as well as others, of course). There are existing crates for these, but I need to look into them to see if they can be used. I started with `graphite2` since it doesn't have any dependencies.

**Comment by pkgw** [comment]
> FYI, the [`servo/rust-harfbuzz`](https://github.com/servo/rust-harfbuzz) crate includes the following `configure` flags, among others: `--without-icu --without-freetype --without-glib`

Yeah, that kind of thing worries me. In the end, it might make sense for us to bundle our own harfbuzz, but have the rest as external dependencies. Based on my packaging experience, the prospect of going around and trying to ensure that a zillion packaging systems all include the right sub-deps in their harfbuzzes seems very unappealing.

**Comment by ratmice** [comment]
yeah, the https://github.com/ratmice/rust-harfbuzz currently does an DEP_ var hack for configuring --with-icu --with-graphite, I think harfbuzz is somewhat painful in the aspect @pkgw mentioned in that even if we can find it from a system library, we still need to do some configure-esque check that it comes with hb-graphite2.h (there is no harfbuzz-graphite.pc like there is for harfbuzz-icu.

The easiest way I know of to do that is to replace it's makefile.cargo with an actual configure script of some sort and perhaps link a dummy library libtectonic_harfbuzz which basically contains nothing but links to the real system harfbuzz if it's built the way we need it, or builds and links to the the "fallback" harfbuzz if it is unavailable

**Comment by pkgw** [comment]
@ratmice I like that idea a lot!

**Comment by spl** [comment]
> The easiest way I know of to do that is to replace it's makefile.cargo with an actual configure script of some sort and perhaps link a dummy library libtectonic_harfbuzz which basically contains nothing but links to the real system harfbuzz if it's built the way we need it, or builds and links to the the "fallback" harfbuzz if the system harfbuzz is unusable.

@ratmice I'm not sure if I completely understand what you mean here, but my plan to create a `harfbuzz-sys` crate that allows you to configure it in the Rust/Cargo way similar to my `graphite2-sys` crate. That is, there is a general flow of trying `pkg-config`, `vcpkg`, etc. and a fallback of a static build. It will also have the option of depending on `graphite2-sys`. Then, there is the option to choose one of the build approaches if you know which one you want. I believe the way I'm doing it is the best in the long run, even it has taken me some time to make sure it works on different targets and package systems.

**Comment by ratmice** [comment]
@spl I will try and explain the troubles i've had with the pkg-config approach (I don't know anything about vcpkg).  Essentially the granularity of pkg-config is the library version in the .pc file, but tectonic depends upon a specific configuration (with graphite2, which is optional and defaults to configuring without it).

So if the pkg-config/vcpkg picks up an installed version of the library, configured in the wrong way, tectonic is going to fail to build.  What was making me doubt the general flow you describe is essentially even when it's found we need to then check everything and potentially provide the fallback.

I definitely agree with your approach, systems like debian are going to frown upon non-system libraries without a real good excuse, earlier in the thread I was basically lamenting the difficulty of providing all the lookup, only to potentially have to fallback to the static build anyways.  But it really does seem like the right thing to do.

**Comment by spl** [comment]
@ratmice Okay, I'm understanding you better. Thanks for that explanation.

Can we identify which systems have HarfBuzz packages with a configuration that won't work for Tectonic?

**Comment by ratmice** [comment]
@spl I don't know what systems would provide one compiled that way,
but I can definitely come up with something that checks it at build time.  Using AC_CHECK_HEADER, this basically runs the cpp with the `#include` and checks the result, if i recall.

I'm hoping that this kind of approach won't interfere with your vcpkg plans (I imagine the static harfbuzz build machinery already relies upon similar checks).

**Comment by pkgw** [comment]
@spl @ratmice Yeah, I think we'd really need a build-time check to decide if the system Harfbuzz was acceptable or not. I'm confident we could devise something that would work in a `build.rs` script, doing the equivalent of Autoconf's `AC_CHECK_HEADER`, `AC_TRY_LINK`, etc.

**Comment by spl** [comment]
> I can definitely come up with something that checks it at build time. Using AC_CHECK_HEADER, this basically runs the cpp with the `#include` and checks the result, if i recall.

Does that only work if the target is the host machine? It would be preferable to have a mechanism that supported cross-compiling.

**Comment by crlf0710** [comment]
@spl if system harfbuzz was not configured satisfying tectonic usage, `harfbuzz/hb-graphite2.h` and `harfbuzz/hb-icu.h` will not be packaged/installed to INCLUDEDIR.

**Comment by pkgw** [comment]
@spl That's actually not any more difficult, I think — the checks are basically test compilations using exactly the same framework that would be used to compile `tectonic/*.c`. You can't *run* any executables that you produce when you're cross-compiling, but you just need to see if they link successfully.

**Comment by spl** [comment]
But what if the actual target machine has HarfBuzz configured differently? I feel like I'm missing something.

**Comment by crlf0710** [comment]
@spl yes, the system harfbuzz is likely dynamic-linked, and if it is configured and built differently, the program will fail to start due to dynamic linking failure. This happens after the successful build and deploy of the program. The rust `openssl`-binding [library](https://github.com/sfackler/rust-openssl/blob/master/openssl-sys/Cargo.toml#L15) suffers from the same program, where they give a separate crate feature called "vendored" to explicitly request the source code of openssl be built locally and statically.

**Comment by pkgw** [comment]
But it's worth pointing out that this can happen with a non-cross build too — the risk is inherent if you're transferring a dynamically linked binary from one machine to another. When you do a cross-compile, your build machine still has to have copies of all the required shared libraries in the target architecture, so as long as those copies are representative of what people on the target platform generally have, there shouldn't be any *additional* wrinkles.

**Comment by spl** [comment]
@crlf0710 Right, that's the static-linking fallback, in which case we don't have the problem.

I guess I'm trying to figure out when will there be a problem with a shared HarfBuzz that is configured without support for ICU, Graphite, etc. I haven't seen any Linux/Homebrew/vcpkg system packages configured that way. So I can only imagine that it happens when HarfBuzz is built and installed manually. I wonder if it's worth the trouble to try to detect that situation.

**Comment by crlf0710** [comment]
For one case, on archlinux, `harfbuzz` and `harfbuzz-icu`(integration) are separate packages.
https://www.archlinux.org/packages/extra/x86_64/harfbuzz/
https://www.archlinux.org/packages/extra/x86_64/harfbuzz-icu/

Maybe someone has installed the former but not the later? I've never experimented with that though.

**Comment by spl** [comment]
@crlf0710 Great! Thanks for the example. Shouldn't `pkg-config` handle that with the requirement for `harfbuzz-icu`?

**Comment by spl** [comment]
That is, either the build will fail if `pkg-config` is required or static linking would be used.

**Comment by ratmice** [comment]
@spl the only instance i know of is issue #318

**Comment by spl** [comment]
@ratmice Thanks, I hadn't seen that before.

I'm thinking it's hard to know what's going on there without more information. And I don't think it's worth trying to support such a strange situation.

Here's a thought. Since this issue would probably only really come up with someone doing a `cargo install tectonic` instead of installing a package through `apt`/`brew`/other, why not make static linking the dependent libraries the default for the crate? That way, the crate always builds regardless of what's on the user's system, and a different configuration can be used for building packages for Debian/Homebrew/other, in which `pkg-config` or something else could be used.

As an aside, the work I plan on doing with the `-sys` crates will support this approach.

**Comment by crlf0710** [comment]
I think statically building and linking everything would be mostly fine. The statically building and deploying of `fontconfig` might be a little tricky, though.

**Comment by ratmice** [comment]
@spl That would seem fine to me :+1:

**Comment by ratmice** [comment]
I wanted to give this one last shot because it seemed like it was fairly close to working on the last go-around

**Comment by pkgw** [comment]
@ratmice Looking at the shell-quoting around where that error happens, I think you need to split the flag on whitespace? Not obvious to me why that would be an issue on the musl build but not the others, though.

**Comment by ratmice** [comment]
@pkgw I believe you are referring to the "-lharfbuzz -lm ...." which are all being sent as a single string,
perhaps splitting that might work.  Honestly though because this is a -o ... -c "tectonic/bibtex.c"
-l/-L options shouldn't even be there until we link libtectonic_c.a/libtectonic_cpp.a.

I will give splitting them a shot though, given the absence of a cc::Build::link_flags or something of the sort.

**Comment by ratmice** [comment]
@pkgw let me know if you want me to try and update the conflicts with master and be more proactive about keeping this up to date.

for what it is worth; I had tried using this branch in a downstream project's CI on azure pipelines,
That wasn't fully successful on every platform (iirc there was an issue on mac os?), but I haven't managed to get back to it yet.

**Comment by pkgw** [comment]
At long last, I think that #724 has fully dealt with this, building on a lot of the groundwork laid here.

**Pull request closed without merging**
