### PR TITLE
`--web-bundle` for v2 CLI: fix #1002 and allow overrides

### LINKED ISSUE #1002: Provide options for V2 cli to override the default bundle_url
When we use `tectonic -X new` or `tectonic -X init` to initiate projects, the output is as follows.
```
note: "version 2" Tectonic command-line interface activated
note: creating new document in directory `xxxx`
note: connecting to https://relay.fullyjustified.net/default_bundle.tar
note: resolved to https://data1.fullyjustified.net/tlextras-2020.0r0.tar
```

It seems that the url is hard coded in
https://github.com/tectonic-typesetting/tectonic/blob/8bf8da71424b2c166dbd4e442c908105ed36bce7/crates/bundles/src/lib.rs#L114-L122

and the config is default using that source
https://github.com/tectonic-typesetting/tectonic/blob/8bf8da71424b2c166dbd4e442c908105ed36bce7/src/config.rs#L194-L202

The source listed above is acceptable for daily usage, but for users in an internal network without access to internet, they may use mirrors or local copy for bundles. However, the command `tectonic -X new` or `tectonic -X init` themselves are default using the hard-coded bundle url to complete initiation, which is meant if the default url is not accessible then the initiation won't be accomplished (usually we waits for minutes and then it throws connection errors and fails).

In the V1 cli, it provides `--web-bundle` to override the default, but in the newer V2 cli, the option is absent. If we provide the option for `tectonic -X new` and `tectonic -X init`, it may be nicer for people unable to access the default bundle url.

### PR DESCRIPTION
**Pull request by bryango**
This PR is split off from #1131. See #1131 for relevant discussions on the web bundle interface.

1. Fixes #1002: It enables us to override the default web bundle for the v2 CLI `tectonic -X new` and `tectonic -X init`, with the usual `--web-bundle` flag
2. Allows overrides: It allows user overrides of the `--web-bundle` by specifying it multiple times. The last specification of `--web-bundle` wins.
3. `tectonic -X build` is special as it never reads from the global config, but only from the local `Tectonic.toml` file, for maximal reproducibility. In this case, the global `--web-bundle` option, if specified, is ignored with a warning.

For a horrible example,
```bash
tectonic \
  --web-bundle "https://this-url-gets-overridden-1" \
  -X \
  --web-bundle "https://this-url-gets-overridden-2" \
  new \
  --web-bundle "https://this-url-gets-overridden-3" \
  --web-bundle "https://this-url-is-actually-used"
```

### CODE REVIEW

**Comment by bryango** [comment]
Whoops, I should write tests, but I don't know how to... :crying_cat_face:

**Comment by doronbehar** [comment]
> Whoops, I should write tests, but I don't know how to... 😿

You may want to do that after upstream approves the intentions of the PR.

I have a question: Is it possible to implement the following behavior:

```
tectonic --web-bundle <URL1> document.tex # Uses URL1
tectonic --web-bundle <URL1> --web-bundle <URL2> document.tex # Uses URL2
tectonic --web-bundle <URL1> -X build # Uses URL1
tectonic --web-bundle <URL1> -X build --web-bundle <URL2> # Uses URL2
tectonic --web-bundle <URL1> -X --web-bundle <URL2> build # Uses URL2
```

This way, the PR would help a lot both Nixpkgs' situation, and all other users. For Nix users, this would allow to wrap Tectonic with `--add-flags` (see [this](https://github.com/NixOS/nixpkgs/blob/4fa61810859ac4bbcdf0e8a1014040fac21a83c7/pkgs/build-support/setup-hooks/make-wrapper.sh#L24-L25)), and for other users it'd allow to simply add a shell alias such as:

```
alias tectonic='tectonic --web-bundle=<URL that matches my biber version>'
```

With the above described behavior to be able to override the web-bundle, a no-Nix user won't need to `unalias` the `tectonic` alias, and Nix users won't need to use the `tectonic-unwrapped` derivation. This is the ideal solution IMO to the issue, that is the least intrusive.

**Comment by doronbehar** [comment]
@bryango this seems to get into great shape! Considering you have added extensive tests, do you think it should be ready for inclusion in Nixpkgs? Along with an additional `makeWrapper` argument `--add-flags`?

**Comment by bryango** [comment]
Hi @doronbehar! Thank you for following along! I think your previous suggestions are great and have been trying to implement them.

> do you think it should be ready for inclusion in Nixpkgs? Along with an additional `makeWrapper` argument `--add-flags`?

This is the eventual goal! I think I finally got everything working, but I am not entirely satisfied about the current resolution. The code feels a bit too hacky... I will try to improve it a bit more, and after some more testing, I think it would be good to go into nixpkgs! But it might take some time :pleading_face:

**Comment by bryango** [comment]
@pkgw @doronbehar @rm-dr Happy new year! I think this is the best I can do, and it's ready for review. The changes may look large and scattered, but in fact half of them are test changes. It is easy to review commit by commit: https://github.com/tectonic-typesetting/tectonic/pull/1132/commits

- Each commit is "bite-sized" and has a clear objective stated in its message.
- The package is buildable at every commit and passes `cargo test`.
- The first few commits are refactors of the current behavior, and the latter ones add new `--web-bundle` options.

**Comment by pkgw** [comment]
Sorry for taking to long to review this :frowning_face:

Upon first read I wasn't a fan of the changes to allow `-X` later in the command line, but I am guessing that the motivation there is to make it possible to set up some kind of alias `mytectonic = tectonic --web-bundle=https://...../` and Things Will Work. So, that seems reasonable.

Likewise I don't *love* having the `-X build` command accept a non-functional `--web-bundle` argument, but the homogeneity also helps with the above.

So I'm going to go ahead and merge this. Sorry again for the lack of responsiveness.

**Comment by bryango** [comment]
Thank you very much for merging this!

> Upon first read I wasn't a fan of the changes to allow `-X` later in the command line, but I am guessing that the motivation there is to make it possible to set up some kind of alias `mytectonic = tectonic --web-bundle=https://...../` and Things Will Work. So, that seems reasonable.

The current solution is indeed ugly, but once v2 CLI has fully taken over, this would hopefully look a bit better!

> So I'm going to go ahead and merge this. Sorry again for the lack of responsiveness.

Please there is no need to apologize! It is already hard enough to work in academics, let alone maintaining many open source codebases where users like me are constantly blabbing for features :laughing: Thank you very much for doing this!

**Pull request merged**
