### PR TITLE
src/engines: fix `lipsum` in TeXLive 2020

### PR DESCRIPTION
**Pull request by pkgw**
As reported in #669, the `lipsum` package is currently broken in TeXLive 2020 because it requests the file `lipsum.ltd.tex` under the name `lipsum.ltd`. At the moment, our file lookup code doesn't try alternative extensions (e.g., adding `.tex`) if the input filename has an extension. Alter this behavior to try adding a new extension, such that `lipsum` should start working again.

I think that this change should, if anything, fix other packages that have been problematic, but we'll have to see what @Mrmaxmeier's tool and my bundle tests report.

### CODE REVIEW

**Comment by pkgw** [comment]
Currently, this fixes 4 documents on tt.ente.ninja but regresses [1702.05590](https://arxiv.org/abs/1702.05590).

**Comment by pkgw** [comment]
Upon examination, this regression looks acceptable. It fixes an earlier error that bibtex had loading a file, which reveals a later error that is unrelated to this change.

**Comment by pkgw** [comment]
Using the new package testing framework in `tectonic-texlive-bundles` (see tectonic-typesetting/tectonic-texlive-bundles#4), I confirm that this fixes `lipsum`.

**Comment by Mrmaxmeier** [comment]
Note: The `tectonic-on-arXiv` bot currently runs the tl2018 bundle. This would have probably fixed more stuff in the tl2020 bundle.
I'll switch the bot to tl2020 once the oxidized fork catches up. :slightly_smiling_face:

**Pull request merged**
